# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavours',
            new_name='Flavour',
        ),
        migrations.RenameModel(
            old_name='Wine_Details',
            new_name='Wine_Detail',
        ),
    ]
