# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0008_wine_detail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_detail',
            name='picture',
            field=models.ImageField(default='not_found.png', upload_to='bottle_images'),
        ),
    ]
