# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0009_auto_20161026_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_detail',
            name='picture',
            field=models.ImageField(upload_to='bottle_images'),
        ),
    ]
