# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0011_auto_20161027_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine_detail',
            name='wine_year',
            field=models.PositiveIntegerField(default=2016),
        ),
    ]
