# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0012_auto_20161027_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=30)),
                ('wine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wine.Wine_Detail')),
            ],
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='cultivar',
            field=models.CharField(choices=[('Sauvignon Blanc', 'Sauvignon Blanc'), ('Chardonnay', 'Chardonnay'), ('Chenin Blanc', 'Chenin Blanc'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Shiraz', 'Shiraz'), ('Merlot', 'Merlot'), ('Pinot Noir', 'Pinot Noir'), ('Pinotage', 'Pinotage')], max_length=30),
        ),
    ]
