# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0013_auto_20161102_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='flavour_picture',
            field=models.ImageField(default='not_found.png', upload_to='flavour_images'),
            preserve_default=False,
        ),
    ]
