# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0015_auto_20161103_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine_detail',
            name='rating_picture',
            field=models.ImageField(default='not_found.png', upload_to='rating_images'),
            preserve_default=False,
        ),
    ]
