# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0002_auto_20160928_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='wine_name',
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='wine_name',
        ),
        migrations.AddField(
            model_name='wine_detail',
            name='cultivar',
            field=models.ManyToManyField(to='Wine.Cultivar'),
        ),
        migrations.AddField(
            model_name='wine_detail',
            name='flavours',
            field=models.ManyToManyField(to='Wine.Flavour'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour_strength',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Barely Noticeable'), (2, 'Somewhat Noticeable'), (3, 'Very Noticeable'), (4, 'Dominant'), (5, 'Overpowering')]),
        ),
    ]
