# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0003_auto_20160928_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine_detail',
            name='flavours',
        ),
    ]
